# Generated by Django 3.2.2 on 2021-08-05 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_student_leads_emp_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hunted_Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee')),
                ('stu_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.student_leads')),
            ],
        ),
    ]
