# Generated by Django 3.2.2 on 2021-08-06 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_hunted_leads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hunted_leads',
            old_name='emp_name',
            new_name='emp_details',
        ),
        migrations.RenameField(
            model_name='hunted_leads',
            old_name='stu_name',
            new_name='stu_details',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='assigin',
        ),
        migrations.RemoveField(
            model_name='student_leads',
            name='emp_name',
        ),
    ]
